
services:
  web:
    build: .
    ports:
      - "5000:5000"
    volumes:
      - ./projects:/app/projects
    environment:
      - REDIS_HOST=redis
      - CELERY_BROKER_URL=redis://redis:6379/0
      - CELERY_RESULT_BACKEND=redis://redis:6379/0
      - BROKER_CONNECTION_RETRY_ON_STARTUP=true
    env_file:
      - .env
    depends_on:
      redis:
        condition: service_healthy
    restart: unless-stopped
    networks:
      - app-network
    healthcheck:
      test: ["CMD", "nc", "-z", "localhost", "5000"]
      interval: 10s
      timeout: 5s
      retries: 3
      start_period: 10s




  redis:
    container_name: redis
    image: redis:latest
    ports:
      - "6379:6379"
    volumes:
      - redis_data:/data
    restart: unless-stopped
    networks:
      - app-network
    healthcheck:
      test: ["CMD", "redis-cli", "ping"]
      interval: 5s
      timeout: 5s
      retries: 5



  celery_worker:
    build: .
    command: celery -A app.celery worker --loglevel=info --uid=1000 --gid=1000
    environment:
      - CELERY_BROKER_URL=redis://redis:6379/0
      - CELERY_RESULT_BACKEND=redis://redis:6379/0
      - REDIS_HOST=redis
      - BROKER_CONNECTION_RETRY_ON_STARTUP=true
    volumes:
      - ./projects:/app/projects
    env_file:
      - .env
    depends_on:
      redis:
        condition: service_healthy
      web:
        condition: service_healthy
    restart: unless-stopped
    networks:
      - app-network




volumes:
  redis_data:
networks:
  app-network:
