version: '3.8'

services:
  test:
    build: .
    command: python -m unittest discover -s tests
    volumes:
      - ./:/app
    env_file:
      - .env
    depends_on:
      redis:
        condition: service_healthy
    networks:
      - app-network
    environment:
      - CELERY_BROKER_URL=redis://redis:6379/0
      - CELERY_RESULT_BACKEND=redis://redis:6379/0
      - REDIS_HOST=redis
      - SOCKETIO_MESSAGE_QUEUE=redis://redis:6379/0
      - SOCKETIO_CORS_ALLOWED_ORIGINS=*
      - PROJECTS_FOLDER=/app/projects

  redis:
    extends:
      file: docker-compose.yml
      service: redis

  celery_worker:
    extends:
      file: docker-compose.yml
      service: celery_worker
    depends_on:
      redis:
        condition: service_healthy

networks:
  app-network:
